all:
  children:
    laptops:
      hosts:
        pop-os:
          ansible_host: 192.168.0.3
    servers:
      hosts:
          g20:
            ansible_host: 192.168.0.4
          raspberrypi:
            ansible_host: 192.168.0.2
    desktops:
      hosts:
        DESKTOP-3N9VVP9: