---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name:
        - bat
        - exa
        - fzf
        - neovim 
        - ripgrep
        - tmux
        - zoxide
        - zsh
