---
- hosts: localhost
  name: autoprovision workstation configuration
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name:
        - bat
        - exa
        - fzf
        - neovim 
        - ripgrep
        - tmux
        - zoxide
        - zsh
  
  - name: change default shell to zsh
    user:
      name: dorian
      shell: /usr/bin/zsh
      state: present

  - name: symlink zshrc
    ansible.builtin.file:
      src: /home/dorian/Projects/ansible-setup/files/zshrc
      path: /home/dorian/.zshrc
      owner: dorian
      group: dorian 
      state: link

  - name: symlink .aliases
    ansible.builtin.file:
      src: /home/dorian/Projects/ansible-setup/files/aliases
      path: /home/dorian/.aliases
      owner: dorian
      group: dorian
      state: link

  - name: add ansible user
    user:
      name: ansible
      system: yes

  - name: set up sudo for ansible user
    copy: 
      src: files/sudoer_ansible
      dest: /etc/sudoers.d/ansible
      owner: root
      group: root
      mode: 0440

  - name: add ansible-pull cron job
    cron:
      name: ansible auto-provision
      user: ansible
      minute: "*/10"
      job: ansible pull -o -U https://github.com/imaginationac/ansible-setup.git
